### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by Moosems** [delrius-euphoria/tkinter-bot#3]
```python
2023-08-16 08:20:22 INFO     discord.client logging in using static token
 * Serving Flask app ''
 * Debug mode: off
Traceback (most recent call last):
  File "/Users/Moosems/Desktop/tkinter-bot/tkinter-bot/main.py", line 35, in <module>
    main()
  File "/Users/Moosems/Desktop/tkinter-bot/tkinter-bot/main.py", line 30, in main
    bot.run(TOKEN)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/discord/client.py", line 860, in run
    asyncio.run(runner())
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/discord/client.py", line 849, in runner
    await self.start(token, reconnect=reconnect)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/discord/client.py", line 777, in start
    await self.login(token)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/discord/client.py", line 609, in login
    raise TypeError(f'expected token to be a str, received {token.__class__.__name__} instead')
TypeError: expected token to be a str, received NoneType instead
```

**Comment by delrius-euphoria** [comment]
Do you have an .env file in your project root directory with the keys required to run a discord bot?

**Comment by Moosems** [comment]
Nope.

**Comment by Moosems** [comment]
Any docs on how to set that up?

**Comment by delrius-euphoria** [comment]
I think this should cover: https://www.writebots.com/discord-bot-token/
